@startuml CasosDeUso
skinparam actorStyle awesome

:Usuario: as usuario 
(Inicio de sesion) as inicioS
(Pagina principal) as principal
(Contraseña o usuario incorrecto) as Cu
(Registro) as re


inicioS --> principal : Digitar contraseña y usuario  correctamente
usuario --> inicioS
inicioS --> Cu : Contraseña o usuario incorrecto 
Cu --> inicioS
inicioS --> re :Click en Registo


@enduml
