@startuml CasosDeUso
skinparam actorStyle awesome

:Usuario: as usuario 
(Iniciar Sesion) as iniciarS
(Inicio de sesion) as inicioS
(Pagina principal) as principal
(Contraseña o usuario incorrecto) as Cu
(Registro) as re


inicioS --> iniciarS :Click en Iniciar Sesion
iniciarS --> principal : Digitar contraseña y usuario  correctamente
usuario --> inicioS : Click en Inicio de Sesion 
iniciarS --> Cu : Contraseña o usuario incorrecto 
Cu --> iniciarS
iniciarS --> re :Click en Registo


@enduml
