@startuml CasosDeUso
skinparam actorStyle awesome

:Usuario: as usuario 
(Notas) as notas
(Agregar Nota) as an
(Confirmar) as con
(Cerrar) as cerr
(Espacio incompleto) as ei

notas--> an :Click en Agregar Nota
an --> con : Mostrar La nota se creo correctamente 
con --> notas :Click en confirmar
an --> cerr
cerr --> notas :Click en Cerrar
usuario --> notas



@enduml
