@startuml CasosDeUso
skinparam actorStyle awesome

:Usuario: as usuario 
(Productos) as pro
(Eliminar Producto) as ep
(Eliminar) as eli
(Cerrar) as cerr
(Si) as si
(No) as no


pro --> ep :Click Eliminar Producto
eli --> si  
si --> pro : Click Si: Mostrar El producto se elimino correctamente 
ep --> eli
eli --> no 
no  --> pro :Click No
ep --> cerr
cerr --> pro :Click Cerrar 
usuario --> pro 



@enduml
