@startuml CasosDeUso
skinparam actorStyle awesome

:Usuario: as usuario 
(Registro) as re
(Registrarme) as regi
(Pagina principal) as principal 
(Contraseña o usuario no valido) as Cu
(Inicio de Sesion ) as is 


re --> regi 
regi --> principal :Click Registrarme: Digitar contraseña y usuario  correctamente
usuario --> re
re --> Cu : Contraseña o usuario no valido 
Cu --> re
re --> is :Click en Inicio de Sesion 


@enduml
