@startuml CasosDeUso
skinparam actorStyle awesome

:Usuario: as usuario 
(Boton "Usuario") as usu
(Perfil) as inicio 
(Configuraciones) as conf
(Cerrar Sesion ) as cs
(Confirmar) as confirmar
(Cancelar) as cancelar

usuario --> usu 
usu --> inicio
usu --> conf
usu --> cs
cs --> confirmar
cs --> cancelar
cancelar --> usu


@enduml
