@startuml CasosDeUso
skinparam actorStyle awesome

:Usuario: as usuario 
(Menu "Usuario") as usu
(Perfil) as per 
(Configuraciones) as conf
(Cerrar Sesion ) as cs
(Confirmar) as confirmar
(Cancelar) as cancelar
(InicioSesion) as Inicio

usuario --> usu :Click Boton Usuario
usu --> per :Click Perfil 
usu --> conf :Click Configuraciones
usu --> cs :Click Cerrar Sesion 
cs --> confirmar 
cs --> cancelar 
cancelar --> usu :Click Cancelar
confirmar --> Inicio :Click Confirmar


@enduml
